name : 'Terraform 2'

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

env:
  BUCKET: japanjot-demo15
  TFSTATE_FILE: new.tfstate 
  DB_TABLE: japanjot-demo1598


jobs:
  terraform:
    name: Terraform
    runs-on:  ubuntu-latest

    

    defaults:
      run:
        working-directory: ./assignment 3.1/mainf

    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id:      ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token:      ${{ secrets.AWS_SESSION_TOKEN }} add token in secrets

          aws-region: us-east-1      

      - name: Terraform Init
        id: init
        run:
          terraform init -reconfigure
         -backend-config="bucket=$BUCKET" 
         -backend-config="key=$TFSTATE_FILE" 
         -backend-config="dynamodb_table=$DB_TABLE"


      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color

      - name: Terraform destroy
        id: destroy
        run:  terraform destroy -auto-approve